---
- name: 创建 prometheus network
  community.docker.docker_network:
    name: "{{ prometheus_network_name }}"

- name: 创建 node exporter directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ docker_compose_dir }}"

- name: 将 docker-compose 文件拷贝到主机指定位置
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/node-exporter-docker-compose.yml"

- name: docker 启动
  ansible.builtin.shell:
    cmd: docker-compose -f {{ docker_compose_dir }}/node-exporter-docker-compose.yml up -d