---
- name: 检查当前环境是 docker 还是 k8s
  ansible.builtin.shell:
    argv:
      - PATH=/usr/bin:/usr/local/bin:/usr/sbin:/usr/local/sbin
      - command
      - -v
      - docker-compose
  register: env_runtime
  ignore_errors: true

- name: Docker 环境部署
  ansible.builtin.include_tasks: docker-deploy.yml
  when: env_runtime is succeeded

- name: K8s 环境部署
  ansible.builtin.include_tasks: k8s-deploy.yml
  when: env_runtime is failed
