---
- name: 创建 prometheus 网络
  community.docker.docker_network:
    name: "{{ prometheus_network_name }}"

- name: 创建 alertmanager 目录
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ docker_compose_dir }}"
    - "{{ alertmanager_config_dir }}"
    - "{{ prometheus_alert_config_dir }}"

- name: 将 docker-compose 文件拷贝到主机指定位置
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/alert-docker-compose.yml"
    mode: "0644"

- name: 配置 alertmanager
  ansible.builtin.template:
    src: templates/alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    mode: "0644"

- name: 配置 prometheus alert
  ansible.builtin.template:
    src: templates/prometheus-alert.conf.j2
    dest: "{{ prometheus_alert_config_dir }}/app.conf"
    mode: "0644"

- name: Docker 启动 alertmanager
  ansible.builtin.command:
    cmd: docker-compose -f {{ docker_compose_dir }}/alert-docker-compose.yml up -d
