---
- name: 创建 prometheus 网络
  community.docker.docker_network:
    name: "{{ prometheus_network_name }}"

- name: 创建 Prometheus 目录
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ docker_compose_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: 将 docker-compose 文件拷贝到主机指定位置
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/prom-docker-compose.yml"

- name: 配置 prometheus
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"

- name: 配置 prometheus alert rules
  ansible.builtin.template:
    src: templates/alerts.yml.j2
    dest: "{{ prometheus_config_dir }}/alerts.yml"
  when: prometheus_alertmanager_configs != ""

- name: Docker 启动 prometheus
  ansible.builtin.command:
    cmd: docker-compose -f {{ docker_compose_dir }}/prom-docker-compose.yml up -d
