---
- name: 创建 prometheus network
  community.docker.docker_network:
    name: "{{ prometheus_network_name }}"

- name: Create blackbox_exporter directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  with_items:
    - "{{ docker_compose_dir }}"
    - "{{ blackbox_exporter_config_dir }}"

- name: 将 docker-compose 文件拷贝到主机指定位置
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ docker_compose_dir }}/blabbox-docker-compose.yml"

- name: 配置 blackbox exporter configuration
  ansible.builtin.template:
    src: templates/blackbox.yml.j2
    dest: "{{ blackbox_exporter_config_dir }}/blackbox.yml"

- name: docker 启动 blackbox_exporter
  ansible.builtin.shell:
    cmd: docker-compose -f {{ docker_compose_dir }}/blackbox-docker-compose.yml up -d
  register: docker-compose-results